local map = require("K").map
map("i", "<M-h>", "<left>", "")
map("i", "<M-j>", "<down>", "")
map("i", "<M-k>", "<up>", "")
map("i", "<M-l>", "<right>", "")
map("n", "H", "^", "")
map("n", "L", "$", "")
map("n", "<C-u>", "9k", "Up 9 lines")
map("n", "<C-d>", "9j", "Down 9 lines")
map("n", "<M-h>", "<C-w>h", "Go to the left window")
map("n", "<M-j>", "<C-w>j", "Go to the bottom window")
map("n", "<M-k>", "<C-w>k", "Go to the upper window")
map("n", "<M-l>", "<C-w>l", "Go to the right window")
map("n", "<M-up>", "<C-w>10+", "The window height increases")
map("n", "<M-down>", "<C-w>10-", "The window height decrease")
map("n", "<M-left>", "<C-w>10<", "The window width decrease")
map("n", "<M-right>", "<C-w>10>", "The window width increases")
map("n", "<leader>bs", "<Cmd>w<CR>", "Save focus buffer")
map("n", "<leader>bq", "<Cmd>wq<CR>", "Save and quit")
map("n", "<leader>bd", "<Cmd>bdelete<CR>", "Delete focus buffer")
map("n", "<Tab>", "<Cmd>bnext<CR>", "Focus next buffer")
map("n", "<S-Tab>", "<Cmd>bprevious<CR>", "Focus previous buffer")
