require("G").map({
  { "i", "<M-h>", "<left>", "" },
  { "i", "<M-j>", "<down>", "" },
  { "i", "<M-k>", "<up>", "" },
  { "i", "<M-l>", "<right>", "" },
  { "n", "H", "^", "" },
  { "n", "L", "$", "" },
  { "n", "<C-u>", "9k", "Up 9 lines" },
  { "n", "<C-d>", "9j", "Down 9 lines" },
  { "n", "<M-h>", "<C-w>h", "Go to the left window" },
  { "n", "<M-j>", "<C-w>j", "Go to the bottom window" },
  { "n", "<M-k>", "<C-w>k", "Go to the upper window" },
  { "n", "<M-l>", "<C-w>l", "Go to the right window" },
  { "n", "<C-up>", "<C-w>10+", "The window height increases" },
  { "n", "<C-down>", "<C-w>10-", "The window height decrease" },
  { "n", "<C-left>", "<C-w>10<", "The window width decrease" },
  { "n", "<C-right>", "<C-w>10>", "The window width increases" },
  { "n", "<leader>bs", ":w<CR>", "Save focus buffer" },
  { "n", "<leader>bq", ":wq<CR>", "Save and quit" },
  { "n", "<leader>bd", ":bdelete<CR>", "Delete focus buffer" },
  { "n", "<Tab>", ":bnext<CR>", "Focus next buffer" },
  { "n", "<S-Tab>", ":bprevious<CR>", "Focus previous buffer" },
})
