local G = require("G")
G.map({
  { "i", "<A-h>", "<left>", "" },
  { "i", "<A-j>", "<down>", "" },
  { "i", "<A-k>", "<up>", "" },
  { "i", "<A-l>", "<right>", "" },
  { "n", "H", "^", "Home of line" },
  { "n", "L", "$", "Last of line" },
  { "n", "<C-u>", "9k", "Up 9 lines" },
  { "n", "<C-d>", "9j", "Down 9 lines" },
  { "n", "<A-h>", "<C-w>h", "Go to the left window" },
  { "n", "<A-j>", "<C-w>j", "Go to the bottom window" },
  { "n", "<A-k>", "<C-w>k", "Go to the upper window" },
  { "n", "<A-l>", "<C-w>l", "Go to the right window" },
  { "n", "<A-H>", "<C-w>H", "Swap the window to the left" },
  { "n", "<A-J>", "<C-w>J", "Swap the window to the bottom" },
  { "n", "<A-K>", "<C-w>K", "Swap the window to the upper" },
  { "n", "<A-L>", "<C-w>L", "Swap the window to the right" },
  { "n", "<A-up>", "<C-w>10+", "The window height increases" },
  { "n", "<A-down>", "<C-w>10-", "The window height decrease" },
  { "n", "<A-left>", "<C-w>10<", "The window width decrease" },
  { "n", "<A-right>", "<C-w>10>", "The window width increases" },
  { "n", "<leader>bs", ":w<CR>", "Save Focus Buffer" },
  { "n", "<leader>ba", ":wa<CR>", "Save All Buffer" },
  { "n", "<leader>bq", ":wqa<CR>", "Save All and Quit" },
  { "n", "<leader>bd", ":bdelete<CR>", "Delete Focus Buffer" },
  { "n", "<Tab>", ":bnext<CR>", "Focus Next Buffer" },
  { "n", "<S-Tab>", ":bprevious<CR>", "Focus Previous Buffer" },
})
