#! /bin/sh

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd >/dev/null || sxhkd &

# dunst &
copyq &
flameshot &
fcitx5 -d &
picom --config ~/.config/picom/picom.conf -b &
feh --bg-fill ~/Pictures/wallpapers/bg_28.jpg
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6
workspaces_multimonitor &

bspc config border_width 2
bspc config window_gap 3

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#db4b4b"
