#! /bin/sh

xsetroot -cursor_name left_ptr
pgrep -x sxhkd > /dev/null || sxhkd &

dunst &
copyq &
flameshot &
fcitx5 -d &
$HOME/.config/polybar/launch.sh
picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/Pictures/wallpapers/bg_28.jpg

bspc monitor -d I II III IV V

bspc config border_width 2
bspc config window_gap 3

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#db4b4b"

bspc rule -a Zathura state=tiled
