#! /bin/sh

xsetroot -cursor_name left_ptr &

pgrep -x sxhkd >/dev/null || sxhkd &

# dunst &
copyq &
fcitx5 &
flameshot &
# youdao-dict &
picom --config ~/.config/picom/picom.conf -b &
feh --bg-fill ~/Pictures/1200056.jpg
$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6
workspaces_multimonitor &

bspc config border_width 2
bspc config window_gap 3

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
